name: Auto-Build
on:
  push

env:
    OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: |
            8
            9

      - name: Test
        run: dotnet test -c release
